# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'CogniwideTask' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod 'Alamofire'
  pod 'RxSwift'
  pod 'RxCocoa'

  # Pods for CogniwideTask

  target 'CogniwideTaskTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'CogniwideTaskUITests' do
    # Pods for testing
  end

end
